kind: PersistentVolume
apiVersion: v1
metadata:
    name: pv-wordpress
    labels:
        type: local
spec:
     capacity:
        storage: 10Gi
     accessModes:
     -  ReadWriteOnce
     hostPath:
         path: /data/wordpress
