apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: namespace-mysql
  labels:
    app: nginx
spec:
  ports:
  - name: http
    port: 3306
    protocol: TCP
    targetPort: 3006
  selector:
    app: wordpress
  type: NodePort
