apiVersion: v1
kind: Service
metadata:
  name: service-wordpress
  namespace: namespace-wordpress
  labels:
    app: service-wordpress
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30000
  selector:
    app: deployment-wordpress
  type: NodePort
