apiVersion: v1
kind: Service
metadata:
  name: service-mysql
  namespace: namespace-mysql
  labels:
    app: service-mysql
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3006
  selector:
    app: deployment-mysql
  type: ClusterIP
